[package]
name = "lots"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["cargo"] }
clap_complete_command = "0.6.1"
eyre = "0.6.12"
rand = "0.10.0"
rayon = "1.11.0"
walkdir = "2.5.0"
